<?php
/* LiangLee Profile Url
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package LiangLeeFramework
 * @Subpackage LiangLee Profile Url
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File start.php
 */
elgg_register_event_handler('init', 'system', 'LiangLeeProfileUrl_init');

function LiangLeeProfileUrl_init() {
/*
 * Register Error if Framework is missing and Pluing is Enabled
 *
 * @access admin
 */
if (!elgg_is_active_plugin('LiangleeFramework')) {
 if (elgg_is_admin_logged_in()) {
 /*
 * Register Error to Admin if framework is missing.
 *
 * @access admin
 */
 register_error(elgg_echo('lianglee:framewrok:miss'));
 } else {
/*
 * Register Error to Users in Code if framework is missing.
 *
 * @access public
 */ 
 register_error(elgg_echo('lianglee:framewrok:miss:code'));	
     }
}  
/*
 * Unregister Admin from topbar
 *
 * @access admin
 */ 
if (elgg_is_admin_logged_in()) {
 
elgg_unregister_menu_item('topbar', 'administration');
/*
 * Register Admin to topbar with herf include backslah ( / )
 *
 * @access admin
 */ 
elgg_register_menu_item('topbar', array(
			'name' => 'administration',
			'href' => 'admin/',
			'text' => elgg_view_icon('settings') . elgg_echo('admin'),
			'priority' => 100,
			'section' => 'alt',
));
}
/*
 * Unregister activity from menu
 *
 * @access public
 */ 
 
elgg_unregister_menu_item('site', 'activity');
/*
 * Register activity to menu with herf include backslah ( / )
 *
 * @access admin
 */ 
 $item = new ElggMenuItem('activity', elgg_echo('activity'), 'activity/');
elgg_register_menu_item('site', $item);

/*
 * Unregister dashboard from topbar
 *
 * @access public
 */ 
elgg_unregister_menu_item('topbar', 'dashboard');
/*
 * Register dashboard to topbar with herf include backslah ( / )
 *
 * @access admin
 */ 
elgg_register_menu_item('topbar', array(
		'name' => 'dashboard',
		'href' => 'dashboard/',
		'text' => elgg_view_icon('home') . elgg_echo('dashboard'),
		'priority' => 450,
		'section' => 'alt',
	));
	
if (!elgg_get_plugin_setting('liang_lee_purl', 'LiangLeeProfileUrl')) {

elgg_register_plugin_hook_handler('index', 'system', 'LiangLeeProfileUrl_rid_error');

} 

if (elgg_get_plugin_setting('liang_lee_purl', 'LiangLeeProfileUrl') == 1) {

elgg_register_plugin_hook_handler('index', 'system', 'LiangLeeProfileUrl_rid_error');

} else {

elgg_unregister_plugin_hook_handler('index', 'system', 'LiangLeeProfileUrl_rid_error');

   }
}

/*
 * Activate index to get rid of Redirected loop errors
 *
 * @access admin
 */ 
function LiangLeeProfileUrl_rid_error($hook, $type, $return, $params) {
	if ($return == true) {

		return $return;
	}

	if (!include_once(dirname(__FILE__) . "/index.php")) {
		return false;
	}
	return true;
}
