<?php
/* LiangLee Profile Url
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package LiangLeeFramework
 * @Subpackage LiangLee Profile Url
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File start.php
 */
elgg_register_event_handler('init', 'system', 'LiangLeeProfileUrl_init');

function LiangLeeProfileUrl_init() {

elgg_register_entity_url_handler('user', 'all', 'lianglee_purl_handler',1);

/*
 * Register Error if Framework is missing and Pluing is Enabled
 *
 * @access admin
 */
if (!elgg_is_active_plugin('LiangleeFramework')) {
 if (elgg_is_admin_logged_in()) {
 /*
 * Register Error to Admin if framework is missing.
 *
 * @access admin
 */
 register_error(elgg_echo('lianglee:framewrok:miss'));
 } else {
/*
 * Register Error to Users in Code if framework is missing.
 *
 * @access public
 */ 
 register_error(elgg_echo('lianglee:framewrok:miss:code'));	
     }
}  
/*
 * Unregister Admin from topbar
 *
 * @access admin
 */ 
if (elgg_is_admin_logged_in()) {
 
elgg_unregister_menu_item('topbar', 'administration');
/*
 * Register Admin to topbar with herf include backslah ( / )
 *
 * @access admin
 */ 
elgg_register_menu_item('topbar', array(
			'name' => 'administration',
			'href' => 'admin/',
			'text' => elgg_view_icon('settings') . elgg_echo('admin'),
			'priority' => 100,
			'section' => 'alt',
));
}
/*
 * Unregister activity from menu
 *
 * @access public
 */ 
 
elgg_unregister_menu_item('site', 'activity');
/*
 * Register activity to menu with herf include backslah ( / )
 *
 * @access admin
 */ 
 $item = new ElggMenuItem('activity', elgg_echo('activity'), 'activity/');
elgg_register_menu_item('site', $item);

/*
 * Unregister dashboard from topbar
 *
 * @access public
 */ 
if (elgg_is_active_plugin('dashboard')) {
 
elgg_unregister_menu_item('topbar', 'dashboard');
/*
 * Register dashboard to topbar with herf include backslah ( / )
 *
 * @access admin
 */ 
elgg_register_menu_item('topbar', array(
		'name' => 'dashboard',
		'href' => 'dashboard/',
		'text' => elgg_view_icon('home') . elgg_echo('dashboard'),
		'priority' => 450,
		'section' => 'alt',
	));
}
if (elgg_get_plugin_setting('liang_lee_purl', 'LiangLeeProfileUrl') == 1) {

elgg_register_plugin_hook_handler('index', 'system', 'LiangLeeProfileUrl_rid_error');

} else {

elgg_unregister_plugin_hook_handler('index', 'system', 'LiangLeeProfileUrl_rid_error');

   }
if (!elgg_get_plugin_setting('liang_lee_purl', 'LiangLeeProfileUrl')) {

elgg_register_plugin_hook_handler('index', 'system', 'LiangLeeProfileUrl_rid_error');

}
if (elgg_is_active_plugin('search')) {

elgg_unregister_page_handler('search', 'search_page_handler');

elgg_register_page_handler('search', 'lianglee_search_page_handler');

}
if (elgg_is_active_plugin('externalpages')) {
$items = array(
'about',
'terms',
'privacy');
foreach($items as $unreg){
elgg_unregister_menu_item('footer',$unreg);
$url = "$unreg/";
$items = new ElggMenuItem($unreg, elgg_echo("expages:$unreg"), $url);
elgg_register_menu_item('footer', $items);
    }
} 
if (elgg_is_active_plugin('members')) {
	$item = new ElggMenuItem('members', elgg_echo('members'), 'members');
	elgg_unregister_menu_item('site', $item);
	
	$reitem = new ElggMenuItem('members', elgg_echo('members'), 'members/');
	elgg_register_menu_item('site', $reitem);
}

}
/*
 * Activate index to get rid of Redirected loop errors
 *
 * @access admin
 */ 
function LiangLeeProfileUrl_rid_error($hook, $type, $return, $params) {
	if ($return == true) {

		return $return;
	}

	if (!include_once(dirname(__FILE__) . "/index.php")) {
		return false;
	}
	return true;
}
/**
 * Page handler for search
 *
 * @param array $page Page elements from core page handler
 * @return bool
 */
function lianglee_search_page_handler($page) {

	// if there is no q set, we're being called from a legacy installation
	// it expects a search by tags.
	// actually it doesn't, but maybe it should.
	// maintain backward compatibility
	if(!get_input('q', get_input('tag', NULL))) {
		set_input('q', $page[0]);
		//set_input('search_type', 'tags');
	}

	$base_dir = elgg_get_plugins_path() . 'LiangLeeProfileUrl/pages/search';

	include_once("$base_dir/index.php");
	return true;
}
/**
 * Profile URL generator for $user->getUrl();
 *
 * @param ElggUser $user
 * @return string User URL
 */
function lianglee_purl_handler($user) {
return elgg_get_site_url() . $user->username;
}