<?php
/* LiangLee Profile Url
 * FrameWork for Liang Lee Plugins
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @package LiangLeeFramework
 * @subpackage LiangLee Profile Url
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright All right reserved Liang Lee 2012.
 * @File settings.php
 */
/**
* Get Version
**/
$plug_ver = LiangLee_version('LiangLeeProfileUrl');
$plug_rel = LiangLee_release('LiangLeeProfileUrl');


/**
* Load Languages
**/
$lleesettings = elgg_echo('lee:settings:own:index');
$liang_lee_copytights = elgg_Echo('lianglee:copyr:12');

/**
* Save settings
**/
$inclib = LiangLee_plugin_path('LiangLeeProfileUrl','lib').'LiangLeeProfileUrl.php';
include($inclib);

$liang_lee_purl = elgg_view('input/dropdown', array(
    'name' =>
    'params[liang_lee_purl]',
    'value' => $vars['entity']->liang_lee_purl,
    'options_values' => array(1 => 'Enable', 2 => 'Disable')));	


$liang_lee_redir = elgg_view("input/text", array(
"name" => "params[lee_purl_redir]", 
"value" => $vars['entity']->lee_purl_redir));	


$lee_purl_entry = elgg_echo('lee:purl:config');
$lee_purl_backup = elgg_echo('lee:purl:backup');
$lee_purl_info = elgg_echo('lee:purl:info:1');
$lee_purl_info2 = elgg_echo('lee:purl:info:2');
$profile_redir_php = elgg_echo('lee:purl:startphp');

$url = "".elgg_get_site_url()."admin/plugin_settings/LiangLeeProfileUrl?backup";
$url2 = "".elgg_get_site_url()."admin/plugin_settings/LiangLeeProfileUrl?configure";

/**
* Setting Page
**/
$settings = <<<__HTML
<style type="text/css">
.style1 {color: #FF0000;font-weight: bold;}
</style>
    <div>
	  <p><strong>$lee_purl_info</strong><a href= $url class="style1"><br />
      $lee_purl_backup</a><br />
	    <strong>$lee_purl_info2</strong><br>
      <a href=$url2 class="style1">$lee_purl_entry</a> </p>
	  <p><i>$lleesettings</i><br>$liang_lee_purl</p><br />
      $profile_redir_php<br/>
	  $liang_lee_redir
		<hr>
		<p><i>$liang_lee_copytights</i>
		<p>Release: $plug_rel</p>
		<p>Version: $plug_ver</p>
</div>
    
</div>
__HTML;
echo $settings;

